# -*- coding: utf-8 -*-
"""icdm_tsne_embedding_visualization_STANDALONE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14j1KfYyIXBvwgpk3qXzO0iegX2GTQZpi

# ICDM VGIB-HGNN t-SNE Embedding Visualization (Standalone)

這份 notebook 不需要接前一份 runtime。只要上傳三個資料檔到 `/content/` 後依序執行即可。
"""

!pip install -q scikit-learn matplotlib pandas numpy torch

"""
Standalone t-SNE / embedding visualization for VGIB-HGNN-Focal.

Purpose
-------
This script trains a lightweight VGIB-HGNN-style patient--species bipartite graph model
on the full cohort for QUALITATIVE visualization, then exports:
  1) pre-bottleneck HGNN embedding h_i t-SNE
  2) post-bottleneck VGIB latent mean mu_i t-SNE
  3) prediction-group t-SNE based on mu_i
  4) CSV coordinates and diagnostic separability metrics

Important
---------
This visualization is intended for paper explanation/diagnostics, NOT as a primary
performance estimate. Your primary metrics should still come from leakage-aware CV.

Expected Colab files
--------------------
/content/data.csv
/content/micro.csv
/content/all_brain_result_1(3).csv

Quick run in Colab
------------------
!pip install -q scikit-learn matplotlib pandas numpy torch
!python /content/icdm_tsne_embedding_visualization_STANDALONE.py
"""

import os
import re
import json
import math
import random
import warnings
from dataclasses import dataclass, asdict
from typing import List, Tuple, Optional, Dict

import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.metrics import (
    roc_auc_score, average_precision_score, precision_score, recall_score, f1_score,
    silhouette_score
)
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression

import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F

warnings.filterwarnings("ignore")


# ============================================================
# 0. Configuration
# ============================================================

@dataclass
class TSNEConfig:
    data_path: str = "/content/data.csv"
    micro_path: str = "/content/micro.csv"
    brain_path: str = "/content/all_brain_result_1(3).csv"
    out_dir: str = "/content/icdm_tsne_visualization_outputs"

    # Data / graph
    n_species: int = 50
    prevalence_min: float = 0.0       # keep species with prevalence > this ratio; 0.0 = no prevalence filter
    edge_rep: str = "log1p"           # "log1p" or "presence"

    # Model
    hidden_dim: int = 64
    latent_dim: int = 32
    dropout: float = 0.20
    beta: float = 5e-4
    gamma: float = 1.0
    alpha_pos: Optional[float] = None # if None, auto class-balanced alpha
    epochs: int = 260
    lr: float = 1e-3
    weight_decay: float = 1e-4
    patience: int = 40
    val_size: float = 0.20

    # Visualization
    seed: int = 42
    perplexity: int = 25
    tsne_n_iter: int = 1500
    use_pca_before_tsne: bool = True
    pca_dim: int = 20
    threshold_policy: str = "max_risk_f1"  # threshold selected on validation split

    # Figure
    dpi: int = 300
    figsize_pair: Tuple[float, float] = (10.5, 4.3)
    figsize_single: Tuple[float, float] = (6.2, 5.0)


CFG = TSNEConfig()


# ============================================================
# 1. Utility functions
# ============================================================

def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)
    return path


def clean_col(c):
    return str(c).strip().replace("\ufeff", "")


def normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [clean_col(c) for c in df.columns]
    return df


def _canonical_col_name(c: str) -> str:
    """Normalize column names for cross-file matching."""
    return re.sub(r"[^a-zA-Z0-9\u4e00-\u9fff]+", "", str(c).strip().lower())


def _normalize_id_values(x: pd.Series) -> pd.Series:
    """Normalize ID values so that 001, 1, and 1.0 can be matched more robustly."""
    def one(v):
        if pd.isna(v):
            return np.nan
        s = str(v).strip().replace("\ufeff", "")
        # convert simple numeric IDs like 001.0 or 1.0 to 1
        try:
            f = float(s)
            if np.isfinite(f) and abs(f - round(f)) < 1e-9:
                return str(int(round(f)))
        except Exception:
            pass
        s = re.sub(r"\s+", "", s)
        s = s.replace("-", "").replace("_", "")
        return s.upper()
    return x.map(one)


def _candidate_id_columns(df: pd.DataFrame) -> List[str]:
    """Return plausible ID columns. We use both name heuristics and value uniqueness."""
    name_keys = ["id", "subject", "sample", "rid", "participant", "編號", "受試", "code", "序號"]
    cols = []
    for c in df.columns:
        cn = _canonical_col_name(c)
        if any(k in cn for k in name_keys):
            cols.append(c)
    # Add columns whose values look identifier-like: mostly unique, not too many missing.
    n = len(df)
    for c in df.columns:
        if c in cols:
            continue
        ser = df[c]
        nonnull = ser.notna().sum()
        if nonnull < max(10, 0.5 * n):
            continue
        nunique = ser.astype(str).nunique(dropna=True)
        uniq_ratio = nunique / max(nonnull, 1)
        # identifier-like columns are usually highly unique; avoid very continuous floats by name later via overlap score
        if uniq_ratio >= 0.70:
            cols.append(c)
    return cols


def find_id_columns(dfs: List[pd.DataFrame], names: List[str] = None) -> Dict[str, str]:
    """Find possibly different ID column names across basic/micro/brain files.

    The previous version required the same column name in all files. Your files can have
    different ID column names, so this function searches by normalized names and by
    overlapping ID values.
    """
    names = names or [f"df{i}" for i in range(len(dfs))]
    common_names = set(_canonical_col_name(c) for c in dfs[0].columns)
    for df in dfs[1:]:
        common_names &= set(_canonical_col_name(c) for c in df.columns)
    preferred = ["id", "subjectid", "sampleid", "rid", "participantid", "編號", "受試者編號"]
    for key in preferred + sorted(common_names):
        cols = []
        ok = True
        for df in dfs:
            matched = [c for c in df.columns if _canonical_col_name(c) == key]
            if not matched:
                ok = False
                break
            cols.append(matched[0])
        if ok:
            return dict(zip(names, cols))

    # Fall back to value-overlap search.
    cand_lists = [_candidate_id_columns(df) for df in dfs]
    if any(len(cands) == 0 for cands in cand_lists):
        raise ValueError(
            "Cannot find candidate ID columns. Please rename your ID columns to the same name, e.g., 'ID'.\n"
            + "Available columns:\n"
            + "\n".join([f"{nm}: {list(df.columns)[:30]}" for nm, df in zip(names, dfs)])
        )

    sets = []
    for df, cands in zip(dfs, cand_lists):
        d = {}
        for c in cands:
            vals = set(_normalize_id_values(df[c]).dropna().astype(str))
            vals.discard("")
            d[c] = vals
        sets.append(d)

    best = None
    best_score = -1
    best_tuple = None
    for c0, s0 in sets[0].items():
        for c1, s1 in sets[1].items():
            inter01 = s0 & s1
            if len(inter01) == 0:
                continue
            for c2, s2 in sets[2].items():
                inter = inter01 & s2
                score = len(inter)
                # slight bonus for columns with ID-like names
                name_bonus = sum(any(k in _canonical_col_name(c) for k in ["id", "subject", "sample", "rid", "編號"]) for c in [c0, c1, c2])
                score2 = score + 0.01 * name_bonus
                if score2 > best_score:
                    best_score = score2
                    best = score
                    best_tuple = (c0, c1, c2)

    if best_tuple is None or best < 10:
        msg = ["Cannot infer matching ID columns with sufficient overlap."]
        for nm, df, cands in zip(names, dfs, cand_lists):
            msg.append(f"{nm} candidate ID columns: {cands[:20]}")
            msg.append(f"{nm} first columns: {list(df.columns)[:30]}")
        msg.append("Please pass/rename a common ID column, for example 'ID', in all three files.")
        raise ValueError("\n".join(msg))

    print("Inferred ID columns by value overlap:", dict(zip(names, best_tuple)), f"| matched subjects={best}")
    return dict(zip(names, best_tuple))


def find_id_column(dfs: List[pd.DataFrame]) -> str:
    """Backward-compatible wrapper. Returns a common ID column only if names match."""
    mapping = find_id_columns(dfs, names=["basic", "micro", "brain"])
    vals = list(mapping.values())
    if len(set(vals)) == 1:
        return vals[0]
    raise ValueError(
        "ID column names differ across files. Use find_id_columns() and rename them to __ID__. "
        f"Detected: {mapping}"
    )

def find_label_column(df: pd.DataFrame) -> str:
    candidates = [
        "Diagnosis", "diagnosis", "DX", "dx", "Group", "group", "Label", "label",
        "ClinicalDiagnosis", "clinical_diagnosis", "disease", "Disease", "診斷", "分組"
    ]
    for c in candidates:
        if c in df.columns:
            return c
    # heuristic: object column with Normal/MCI/Dementia-like strings
    for c in df.columns:
        vals = df[c].dropna().astype(str).str.lower().unique()
        joined = " ".join(vals[:20])
        if any(k in joined for k in ["normal", "mci", "dementia", "control", "nc"]):
            return c
    raise ValueError("Cannot find diagnosis/label column. Please rename it to 'Diagnosis'.")


def map_diagnosis_to_binary(s):
    """
    Map diagnosis labels to binary screening labels.

    Binary task:
    - Normal = 0
    - MCI / Dementia = 1
    - SCD / 999 / unknown labels are treated as missing and filtered out later.
    """
    raw = s.astype(str).str.strip()
    low = raw.str.lower()

    y = pd.Series(np.nan, index=s.index, dtype=float)

    normal_values = {
        "normal", "nc", "control", "healthy", "0", "正常"
    }

    risk_values = {
        "mci", "mild cognitive impairment", "dementia", "ad",
        "alzheimers", "alzheimer", "1", "失智症", "輕度認知障礙"
    }

    missing_values = {
        "999", "nan", "none", "missing", "", "unknown", "na",
        "scd", "subjective cognitive decline", "主觀認知下降"
    }

    y[low.isin(normal_values)] = 0
    y[low.isin(risk_values)] = 1
    y[low.isin(missing_values)] = np.nan

    bad = raw[y.isna() & ~low.isin(missing_values)].unique()
    if len(bad) > 0:
        print("[WARN] Unrecognized diagnosis values treated as missing:", bad[:20])

    return y


def numeric_feature_columns(df: pd.DataFrame, exclude: List[str]) -> List[str]:
    cols = []
    for c in df.columns:
        if c in exclude:
            continue
        x = pd.to_numeric(df[c], errors="coerce")
        if x.notna().sum() > 0:
            cols.append(c)
    return cols


def make_unique_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Ensure unique column names after merge."""
    seen = {}
    new_cols = []
    for c in df.columns:
        if c not in seen:
            seen[c] = 0
            new_cols.append(c)
        else:
            seen[c] += 1
            new_cols.append(f"{c}__dup{seen[c]}")
    df = df.copy()
    df.columns = new_cols
    return df


# ============================================================
# 2. Load and prepare data
# ============================================================

def load_and_prepare_data(cfg: TSNEConfig):
    basic = normalize_columns(pd.read_csv(cfg.data_path))
    micro = normalize_columns(pd.read_csv(cfg.micro_path))
    brain = normalize_columns(pd.read_csv(cfg.brain_path))

    id_cols = find_id_columns([basic, micro, brain], names=["basic", "micro", "brain"])
    label_col = find_label_column(basic)

    # Standardize possibly different ID column names to a shared __ID__ key.
    basic_use = basic.copy()
    micro_use = micro.copy()
    brain_use = brain.copy()

    basic_use["__ID__"] = _normalize_id_values(basic_use[id_cols["basic"]])
    micro_use["__ID__"] = _normalize_id_values(micro_use[id_cols["micro"]])
    brain_use["__ID__"] = _normalize_id_values(brain_use[id_cols["brain"]])

    # Drop original ID columns if they are not __ID__, to prevent duplicated merge keys.
    for df, old in [(basic_use, id_cols["basic"]), (micro_use, id_cols["micro"]), (brain_use, id_cols["brain"] )]:
        if old in df.columns and old != "__ID__":
            # keep original ID only if it is also useful metadata; it is excluded from features below
            pass

    id_col = "__ID__"

    # Avoid duplicate label columns from brain/micro if any.
    for df in [micro_use, brain_use]:
        for c in list(df.columns):
            if c == id_col:
                continue
            if _canonical_col_name(c) in [_canonical_col_name(label_col), "diagnosis", "label", "group", "dx"]:
                df.drop(columns=[c], inplace=True)

    merged = basic_use.merge(brain_use, on=id_col, how="inner", suffixes=("", "_brain"))
    merged = merged.merge(micro_use, on=id_col, how="inner", suffixes=("", "_micro"))
    merged = make_unique_columns(merged)

    if merged.empty:
        raise ValueError(
            "The three files produced an empty merge after ID normalization. "
            f"Detected ID columns: {id_cols}. Please check whether IDs refer to the same subjects."
        )

    # If label_col was duplicated/renamed after merge, recover it.
    if label_col not in merged.columns:
        label_candidates = [c for c in merged.columns if c.startswith(label_col)]
        if not label_candidates:
            raise ValueError(f"Label column {label_col} was not found after merging.")
        label_col_m = label_candidates[0]
    else:
        label_col_m = label_col

    # Map Diagnosis to the binary screening target and drop labels that are
    # outside the Normal-vs-Risk task, such as SCD or unknown code 999.
    y_series = map_diagnosis_to_binary(merged[label_col_m])
    valid_mask = y_series.notna().values

    if valid_mask.sum() < len(merged):
        print(f"[INFO] Dropping {len(merged) - valid_mask.sum()} subjects with SCD/999/unknown diagnosis.")

    merged = merged.loc[valid_mask].reset_index(drop=True)
    y = y_series.loc[valid_mask].astype(int).values

    # Determine feature source columns from original tables.
    basic_exclude = [id_cols["basic"], label_col, id_col]
    brain_exclude = [id_cols["brain"], label_col, id_col]
    micro_exclude = [id_cols["micro"], label_col, id_col]
    basic_cols = numeric_feature_columns(basic_use, exclude=basic_exclude)
    brain_cols_raw = numeric_feature_columns(brain_use, exclude=brain_exclude)
    micro_cols_raw = numeric_feature_columns(micro_use, exclude=micro_exclude)

    # Map raw columns to merged columns after suffixing; exact match first, then suffix variants.
    def map_cols_to_merged(raw_cols):
        mapped = []
        for c in raw_cols:
            if c in merged.columns:
                mapped.append(c)
            elif f"{c}_brain" in merged.columns:
                mapped.append(f"{c}_brain")
            elif f"{c}_micro" in merged.columns:
                mapped.append(f"{c}_micro")
            else:
                matches = [m for m in merged.columns if m.startswith(c + "__dup")]
                if matches:
                    mapped.append(matches[0])
        return mapped

    basic_m = map_cols_to_merged(basic_cols)
    brain_m = map_cols_to_merged(brain_cols_raw)
    micro_m = map_cols_to_merged(micro_cols_raw)

    # Remove overlap: microbiome columns should come from micro file; patient features are basic + brain.
    patient_cols = []
    for c in basic_m + brain_m:
        if c not in patient_cols and c in merged.columns and c != id_col:
            patient_cols.append(c)
    micro_cols = [c for c in micro_m if c in merged.columns and c not in patient_cols and c != id_col]

    if len(patient_cols) == 0:
        raise ValueError("No numeric patient features were detected after merging.")
    if len(micro_cols) == 0:
        raise ValueError("No numeric microbiome features were detected after merging.")

    # Coerce numeric matrices
    X_patient_raw = merged[patient_cols].apply(pd.to_numeric, errors="coerce")
    M_raw = merged[micro_cols].apply(pd.to_numeric, errors="coerce").fillna(0.0)

    # Species prevalence and variance selection
    prevalence = (M_raw > 0).mean(axis=0)
    keep_prev = prevalence[prevalence > cfg.prevalence_min].index.tolist()
    if len(keep_prev) < cfg.n_species:
        keep_prev = M_raw.columns.tolist()
    variances = M_raw[keep_prev].var(axis=0).sort_values(ascending=False)
    selected_species = variances.index[:cfg.n_species].tolist()
    M_sel = M_raw[selected_species].copy()

    # Impute/scale patient features
    imp = SimpleImputer(strategy="median")
    scaler = StandardScaler()
    X_patient = scaler.fit_transform(imp.fit_transform(X_patient_raw))

    # Species matrix / edge attributes
    M_values = M_sel.values.astype(np.float32)
    if cfg.edge_rep == "presence":
        edge_values = (M_values > 0).astype(np.float32)
    elif cfg.edge_rep == "log1p":
        edge_values = np.log1p(np.maximum(M_values, 0)).astype(np.float32)
    else:
        raise ValueError("cfg.edge_rep must be 'log1p' or 'presence'.")

    print("========== Data Summary ==========")
    print("basic:", basic.shape, "micro:", micro.shape, "brain:", brain.shape)
    print("merged:", merged.shape)
    print("Detected ID columns:", id_cols)
    print("Using standardized ID column: __ID__ | label column:", label_col_m)
    print("Diagnosis counts:")
    print(pd.Series(y).map({0:"Normal", 1:"Risk"}).value_counts())
    print("patient features:", X_patient.shape[1], "selected species:", len(selected_species))
    print("==================================")

    meta = pd.DataFrame({"row_index": np.arange(len(merged)), "id": merged[id_col].values, "y": y})
    if label_col_m in merged.columns:
        meta["diagnosis_raw"] = merged[label_col_m].values

    return {
        "merged": merged,
        "meta": meta,
        "y": y.astype(int),
        "X_patient": X_patient.astype(np.float32),
        "M_edge": edge_values.astype(np.float32),
        "patient_cols": patient_cols,
        "selected_species": selected_species,
        "id_col": id_col,
        "raw_id_cols": id_cols,
        "label_col": label_col_m,
    }


# ============================================================
# 3. Build bipartite graph tensors
# ============================================================

def build_edges_from_matrix(M_edge: np.ndarray):
    """Return patient indices, species indices, edge attrs for nonzero patient-species entries."""
    p_idx, s_idx = np.nonzero(M_edge > 0)
    e_attr = M_edge[p_idx, s_idx]
    if len(p_idx) == 0:
        raise ValueError("No nonzero patient-species edges found. Check microbiome file or edge_rep.")
    return (
        torch.tensor(p_idx, dtype=torch.long),
        torch.tensor(s_idx, dtype=torch.long),
        torch.tensor(e_attr.reshape(-1, 1), dtype=torch.float32),
    )


# ============================================================
# 4. Model
# ============================================================

class FocalLoss(nn.Module):
    def __init__(self, gamma=1.0, alpha_pos=None, eps=1e-8):
        super().__init__()
        self.gamma = gamma
        self.alpha_pos = alpha_pos
        self.eps = eps

    def forward(self, logits, y):
        y = y.float()
        p = torch.sigmoid(logits).clamp(self.eps, 1 - self.eps)
        pt = torch.where(y == 1, p, 1 - p)
        if self.alpha_pos is None:
            alpha_t = torch.ones_like(y)
        else:
            alpha_pos = float(self.alpha_pos)
            alpha_t = torch.where(y == 1, torch.full_like(y, alpha_pos), torch.full_like(y, 1 - alpha_pos))
        loss = -alpha_t * ((1 - pt) ** self.gamma) * torch.log(pt)
        return loss.mean()


class SimpleVGIBHGNN(nn.Module):
    """Small self-contained patient--species HGNN with attention + VGIB."""
    def __init__(self, patient_dim, n_species, hidden_dim=64, latent_dim=32, dropout=0.2):
        super().__init__()
        self.patient_in = nn.Linear(patient_dim, hidden_dim)
        self.species_emb = nn.Embedding(n_species, hidden_dim)
        self.edge_proj = nn.Linear(1, hidden_dim)

        self.att_vec = nn.Parameter(torch.empty(hidden_dim * 3))
        nn.init.xavier_uniform_(self.att_vec.view(1, -1))

        self.self_lin = nn.Linear(hidden_dim, hidden_dim)
        self.msg_lin = nn.Linear(hidden_dim, hidden_dim)
        self.norm = nn.LayerNorm(hidden_dim)
        self.dropout = nn.Dropout(dropout)

        self.mu = nn.Linear(hidden_dim, latent_dim)
        self.logvar = nn.Linear(hidden_dim, latent_dim)
        self.classifier = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim // 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim // 2, 1),
        )

    def forward(self, x_patient, p_idx, s_idx, edge_attr, sample=True):
        N = x_patient.size(0)
        hp0 = F.relu(self.patient_in(x_patient))
        hs = self.species_emb.weight

        hp_e = hp0[p_idx]
        hs_e = hs[s_idx]
        ea_e = F.relu(self.edge_proj(edge_attr))

        att_in = torch.cat([hp_e, hs_e, ea_e], dim=1)
        scores = F.leaky_relu(torch.matmul(att_in, self.att_vec), negative_slope=0.2)

        # Softmax over species neighbors per patient. N is small, loop is okay and dependency-free.
        alpha = torch.zeros_like(scores)
        for i in torch.unique(p_idx):
            mask = (p_idx == i)
            alpha[mask] = torch.softmax(scores[mask], dim=0)

        msg_e = self.msg_lin(hs_e + ea_e) * alpha.unsqueeze(1)
        aggr = torch.zeros(N, msg_e.size(1), device=x_patient.device)
        aggr.index_add_(0, p_idx, msg_e)

        h = self.norm(F.relu(self.self_lin(hp0) + aggr))
        h = self.dropout(h)

        mu = self.mu(h)
        logvar = self.logvar(h).clamp(-8, 8)
        if sample:
            eps = torch.randn_like(mu)
            z = mu + torch.exp(0.5 * logvar) * eps
        else:
            z = mu
        logits = self.classifier(z).squeeze(-1)
        return logits, h, mu, logvar


def kl_diag_gaussian(mu, logvar):
    return -0.5 * torch.mean(torch.sum(1 + logvar - mu.pow(2) - logvar.exp(), dim=1))


# ============================================================
# 5. Training and thresholding
# ============================================================

def choose_threshold(y_true, prob, policy="max_risk_f1"):
    y_true = np.asarray(y_true).astype(int)
    prob = np.asarray(prob).astype(float)
    thresholds = np.unique(np.concatenate([np.linspace(0.01, 0.99, 300), prob]))
    best_t, best_score = 0.5, -1
    for t in thresholds:
        pred = (prob >= t).astype(int)
        rec = recall_score(y_true, pred, zero_division=0)
        prec = precision_score(y_true, pred, zero_division=0)
        f1 = f1_score(y_true, pred, zero_division=0)
        if policy == "max_risk_f1":
            score = f1
        elif policy == "max_recall_precision_floor":
            score = rec if prec >= 0.5 else -1
        else:
            score = f1
        if score > best_score:
            best_score = score
            best_t = float(t)
    return best_t


def compute_metrics(y_true, prob, threshold=0.5):
    pred = (prob >= threshold).astype(int)
    return {
        "AUC": roc_auc_score(y_true, prob) if len(np.unique(y_true)) > 1 else np.nan,
        "PR_AUC": average_precision_score(y_true, prob),
        "Risk_Recall": recall_score(y_true, pred, zero_division=0),
        "Risk_Precision": precision_score(y_true, pred, zero_division=0),
        "Risk_F1": f1_score(y_true, pred, zero_division=0),
        "threshold": threshold,
    }


def train_model_for_visualization(data, cfg: TSNEConfig):
    set_seed(cfg.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("Using device:", device)

    X = data["X_patient"]
    y = data["y"]
    M_edge = data["M_edge"]
    n_species = M_edge.shape[1]

    train_idx, val_idx = train_test_split(
        np.arange(len(y)), test_size=cfg.val_size, random_state=cfg.seed, stratify=y
    )

    x_t = torch.tensor(X, dtype=torch.float32, device=device)
    y_t = torch.tensor(y, dtype=torch.float32, device=device)
    p_idx, s_idx, edge_attr = build_edges_from_matrix(M_edge)
    p_idx = p_idx.to(device)
    s_idx = s_idx.to(device)
    edge_attr = edge_attr.to(device)

    # class-balanced alpha for focal loss
    if cfg.alpha_pos is None:
        pos_rate = y[train_idx].mean()
        alpha_pos = float(1 - pos_rate)
    else:
        alpha_pos = cfg.alpha_pos

    model = SimpleVGIBHGNN(
        patient_dim=X.shape[1],
        n_species=n_species,
        hidden_dim=cfg.hidden_dim,
        latent_dim=cfg.latent_dim,
        dropout=cfg.dropout,
    ).to(device)

    criterion = FocalLoss(gamma=cfg.gamma, alpha_pos=alpha_pos)
    opt = torch.optim.AdamW(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)

    train_idx_t = torch.tensor(train_idx, dtype=torch.long, device=device)
    val_idx_t = torch.tensor(val_idx, dtype=torch.long, device=device)

    best_state = None
    best_val = -1
    bad = 0
    history = []

    for epoch in range(1, cfg.epochs + 1):
        model.train()
        opt.zero_grad()
        logits, h, mu, logvar = model(x_t, p_idx, s_idx, edge_attr, sample=True)
        focal = criterion(logits[train_idx_t], y_t[train_idx_t])
        kl = kl_diag_gaussian(mu[train_idx_t], logvar[train_idx_t])
        loss = focal + cfg.beta * kl
        loss.backward()
        opt.step()

        model.eval()
        with torch.no_grad():
            logits_eval, h_eval, mu_eval, logvar_eval = model(x_t, p_idx, s_idx, edge_attr, sample=False)
            prob_val = torch.sigmoid(logits_eval[val_idx_t]).detach().cpu().numpy()
            y_val = y[val_idx]
            try:
                val_pr = average_precision_score(y_val, prob_val)
            except Exception:
                val_pr = 0.0
            val_thr = choose_threshold(y_val, prob_val, policy=cfg.threshold_policy)
            val_f1 = f1_score(y_val, (prob_val >= val_thr).astype(int), zero_division=0)
            monitor = val_f1 + 0.05 * val_pr

        history.append({"epoch": epoch, "loss": float(loss.item()), "val_pr_auc": float(val_pr), "val_f1": float(val_f1), "monitor": float(monitor)})

        if monitor > best_val:
            best_val = monitor
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            bad = 0
        else:
            bad += 1
        if bad >= cfg.patience:
            print(f"Early stopping at epoch {epoch}; best monitor={best_val:.4f}")
            break
        if epoch % 50 == 0:
            print(f"Epoch {epoch:03d} | loss={loss.item():.4f} | val PR-AUC={val_pr:.3f} | val F1={val_f1:.3f}")

    if best_state is not None:
        model.load_state_dict(best_state)

    model.eval()
    with torch.no_grad():
        logits_all, h_all, mu_all, logvar_all = model(x_t, p_idx, s_idx, edge_attr, sample=False)
        prob_all = torch.sigmoid(logits_all).detach().cpu().numpy()
        h_np = h_all.detach().cpu().numpy()
        mu_np = mu_all.detach().cpu().numpy()
        logvar_np = logvar_all.detach().cpu().numpy()

        logits_val, _, _, _ = model(x_t, p_idx, s_idx, edge_attr, sample=False)
        prob_val = torch.sigmoid(logits_val[val_idx_t]).detach().cpu().numpy()
        threshold = choose_threshold(y[val_idx], prob_val, policy=cfg.threshold_policy)

    metrics_all = compute_metrics(y, prob_all, threshold=threshold)
    print("Visualization model metrics on full cohort (qualitative only):")
    print({k: round(v, 4) if isinstance(v, float) else v for k, v in metrics_all.items()})

    return {
        "model": model,
        "history": pd.DataFrame(history),
        "prob": prob_all,
        "threshold": threshold,
        "h": h_np,
        "mu": mu_np,
        "logvar": logvar_np,
        "train_idx": train_idx,
        "val_idx": val_idx,
        "metrics_all": metrics_all,
    }


# ============================================================
# 6. t-SNE and diagnostics
# ============================================================

def tsne_2d(X, cfg: TSNEConfig, seed_offset=0):
    X = np.asarray(X, dtype=np.float32)
    Xz = StandardScaler().fit_transform(X)
    if cfg.use_pca_before_tsne and Xz.shape[1] > cfg.pca_dim:
        Xz = PCA(n_components=cfg.pca_dim, random_state=cfg.seed).fit_transform(Xz)
    n = Xz.shape[0]
    perplexity = min(cfg.perplexity, max(5, (n - 1) // 3))
    # sklearn parameter changed from n_iter to max_iter in newer versions.
    try:
        emb = TSNE(
            n_components=2,
            perplexity=perplexity,
            learning_rate="auto",
            init="pca",
            max_iter=cfg.tsne_n_iter,
            random_state=cfg.seed + seed_offset,
        ).fit_transform(Xz)
    except TypeError:
        emb = TSNE(
            n_components=2,
            perplexity=perplexity,
            learning_rate="auto",
            init="pca",
            n_iter=cfg.tsne_n_iter,
            random_state=cfg.seed + seed_offset,
        ).fit_transform(Xz)
    return emb


def separability_diagnostics(X, y, name):
    X = np.asarray(X, dtype=np.float32)
    y = np.asarray(y).astype(int)
    rows = []
    try:
        sil = silhouette_score(StandardScaler().fit_transform(X), y)
    except Exception:
        sil = np.nan

    try:
        clf = LogisticRegression(max_iter=2000, class_weight="balanced")
        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        aucs = cross_val_score(clf, StandardScaler().fit_transform(X), y, cv=cv, scoring="roc_auc")
        auc_mean = aucs.mean()
        auc_std = aucs.std()
    except Exception:
        auc_mean, auc_std = np.nan, np.nan

    return {
        "embedding": name,
        "silhouette_by_true_label": sil,
        "linear_probe_auc_mean": auc_mean,
        "linear_probe_auc_std": auc_std,
    }


def prediction_group_labels(y, prob, threshold):
    pred = (prob >= threshold).astype(int)
    groups = []
    for yi, pi in zip(y, pred):
        if yi == 0 and pi == 0:
            groups.append("Correct Normal")
        elif yi == 1 and pi == 1:
            groups.append("Correct Risk")
        elif yi == 0 and pi == 1:
            groups.append("Normal-to-Risk")
        else:
            groups.append("Risk-to-Normal")
    return np.array(groups)


# ============================================================
# 7. Plotting
# ============================================================

PALETTE_LABEL = {0: "#4C78A8", 1: "#E45756"}
PALETTE_GROUP = {
    "Correct Normal": "#4C78A8",
    "Correct Risk": "#E45756",
    "Normal-to-Risk": "#F2A541",
    "Risk-to-Normal": "#7B61FF",
}


def setup_plot_style():
    plt.rcParams.update({
        "figure.dpi": 120,
        "savefig.dpi": 300,
        "savefig.bbox": "tight",
        "font.size": 10,
        "axes.titlesize": 11,
        "axes.labelsize": 10,
        "legend.fontsize": 9,
        "axes.spines.top": False,
        "axes.spines.right": False,
    })


def plot_before_after(emb_h, emb_mu, y, out_dir, cfg):
    setup_plot_style()
    fig, axes = plt.subplots(1, 2, figsize=cfg.figsize_pair)
    titles = ["HGNN embedding before VGIB", "VGIB latent mean after bottleneck"]
    embs = [emb_h, emb_mu]
    for ax, emb, title in zip(axes, embs, titles):
        for label, name in [(0, "Normal"), (1, "Risk")]:
            mask = y == label
            ax.scatter(emb[mask, 0], emb[mask, 1], s=26, alpha=0.82, label=name,
                       c=PALETTE_LABEL[label], edgecolors="white", linewidths=0.35)
        ax.set_title(title)
        ax.set_xlabel("t-SNE 1")
        ax.set_ylabel("t-SNE 2")
        ax.legend(frameon=False)
    fig.suptitle("Patient representation visualization before and after VGIB", y=1.02, fontsize=12, fontweight="bold")
    png = os.path.join(out_dir, "TSNE_01_before_after_vgib_true_label.png")
    pdf = os.path.join(out_dir, "TSNE_01_before_after_vgib_true_label.pdf")
    fig.savefig(png)
    fig.savefig(pdf)
    plt.close(fig)
    return png, pdf


def plot_prediction_groups(emb_mu, groups, out_dir, cfg):
    setup_plot_style()
    fig, ax = plt.subplots(1, 1, figsize=cfg.figsize_single)
    order = ["Correct Normal", "Correct Risk", "Normal-to-Risk", "Risk-to-Normal"]
    for g in order:
        mask = groups == g
        if mask.sum() == 0:
            continue
        ax.scatter(emb_mu[mask, 0], emb_mu[mask, 1], s=30, alpha=0.85, label=f"{g} (n={mask.sum()})",
                   c=PALETTE_GROUP[g], edgecolors="white", linewidths=0.35)
    ax.set_title("VGIB latent space by prediction agreement group", fontweight="bold")
    ax.set_xlabel("t-SNE 1")
    ax.set_ylabel("t-SNE 2")
    ax.legend(frameon=False, loc="best")
    png = os.path.join(out_dir, "TSNE_02_vgib_prediction_groups.png")
    pdf = os.path.join(out_dir, "TSNE_02_vgib_prediction_groups.pdf")
    fig.savefig(png)
    fig.savefig(pdf)
    plt.close(fig)
    return png, pdf


def plot_probability_overlay(emb_mu, prob, out_dir, cfg):
    setup_plot_style()
    fig, ax = plt.subplots(1, 1, figsize=cfg.figsize_single)
    sc = ax.scatter(emb_mu[:, 0], emb_mu[:, 1], s=32, c=prob, cmap="viridis", alpha=0.88,
                    edgecolors="white", linewidths=0.25)
    ax.set_title("VGIB latent space colored by predicted risk", fontweight="bold")
    ax.set_xlabel("t-SNE 1")
    ax.set_ylabel("t-SNE 2")
    cb = plt.colorbar(sc, ax=ax)
    cb.set_label("Predicted risk probability")
    png = os.path.join(out_dir, "TSNE_03_vgib_predicted_risk_probability.png")
    pdf = os.path.join(out_dir, "TSNE_03_vgib_predicted_risk_probability.pdf")
    fig.savefig(png)
    fig.savefig(pdf)
    plt.close(fig)
    return png, pdf


# ============================================================
# 8. Main runner
# ============================================================

def run_vgib_tsne_visualization(
    data_path="/content/data.csv",
    micro_path="/content/micro.csv",
    brain_path="/content/all_brain_result_1(3).csv",
    out_dir="/content/icdm_tsne_visualization_outputs",
    edge_rep="log1p",
    beta=5e-4,
    gamma=1.0,
    seed=42,
    perplexity=25,
    epochs=260,
    hidden_dim=64,
    latent_dim=32,
    n_species=50,
    threshold_policy="max_risk_f1",
):
    cfg = TSNEConfig(
        data_path=data_path,
        micro_path=micro_path,
        brain_path=brain_path,
        out_dir=out_dir,
        edge_rep=edge_rep,
        beta=beta,
        gamma=gamma,
        seed=seed,
        perplexity=perplexity,
        epochs=epochs,
        hidden_dim=hidden_dim,
        latent_dim=latent_dim,
        n_species=n_species,
        threshold_policy=threshold_policy,
    )
    ensure_dir(cfg.out_dir)
    set_seed(cfg.seed)

    with open(os.path.join(cfg.out_dir, "TSNE_config.json"), "w", encoding="utf-8") as f:
        json.dump(asdict(cfg), f, indent=2)

    data = load_and_prepare_data(cfg)
    fit = train_model_for_visualization(data, cfg)

    print("Computing t-SNE coordinates...")
    emb_h = tsne_2d(fit["h"], cfg, seed_offset=0)
    emb_mu = tsne_2d(fit["mu"], cfg, seed_offset=100)

    y = data["y"]
    prob = fit["prob"]
    threshold = fit["threshold"]
    groups = prediction_group_labels(y, prob, threshold)

    # Coordinates CSV
    coords = data["meta"].copy()
    coords["prob"] = prob
    coords["pred"] = (prob >= threshold).astype(int)
    coords["prediction_group"] = groups
    coords["h_tsne_1"] = emb_h[:, 0]
    coords["h_tsne_2"] = emb_h[:, 1]
    coords["mu_tsne_1"] = emb_mu[:, 0]
    coords["mu_tsne_2"] = emb_mu[:, 1]
    coords_path = os.path.join(cfg.out_dir, "TSNE_embedding_coordinates.csv")
    coords.to_csv(coords_path, index=False)

    # Diagnostics
    diag = []
    diag.append(separability_diagnostics(fit["h"], y, "HGNN_pre_bottleneck_h"))
    diag.append(separability_diagnostics(fit["mu"], y, "VGIB_latent_mean_mu"))
    diag_df = pd.DataFrame(diag)
    diag_path = os.path.join(cfg.out_dir, "TSNE_embedding_separation_diagnostics.csv")
    diag_df.to_csv(diag_path, index=False)

    # Model metrics and counts
    metrics_df = pd.DataFrame([fit["metrics_all"]])
    metrics_path = os.path.join(cfg.out_dir, "TSNE_visualization_model_metrics.csv")
    metrics_df.to_csv(metrics_path, index=False)

    group_counts = pd.DataFrame(pd.Series(groups).value_counts()).reset_index()
    group_counts.columns = ["prediction_group", "n"]
    group_counts_path = os.path.join(cfg.out_dir, "TSNE_prediction_group_counts.csv")
    group_counts.to_csv(group_counts_path, index=False)

    fit["history"].to_csv(os.path.join(cfg.out_dir, "TSNE_training_history.csv"), index=False)

    # Figures
    fig1 = plot_before_after(emb_h, emb_mu, y, cfg.out_dir, cfg)
    fig2 = plot_prediction_groups(emb_mu, groups, cfg.out_dir, cfg)
    fig3 = plot_probability_overlay(emb_mu, prob, cfg.out_dir, cfg)

    # Zip outputs
    zip_path = os.path.join(cfg.out_dir, "icdm_tsne_visualization_outputs.zip")
    try:
        import zipfile
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for root, _, files in os.walk(cfg.out_dir):
                for fn in files:
                    if fn.endswith(".zip"):
                        continue
                    fp = os.path.join(root, fn)
                    zf.write(fp, arcname=os.path.relpath(fp, cfg.out_dir))
    except Exception as e:
        print("Could not create zip:", e)
        zip_path = None

    print("\nSaved outputs to:", cfg.out_dir)
    print("Coordinates:", coords_path)
    print("Diagnostics:", diag_path)
    print("Figures:")
    print(" -", fig1[0])
    print(" -", fig2[0])
    print(" -", fig3[0])
    if zip_path:
        print("Zip:", zip_path)

    return {
        "config": cfg,
        "data": data,
        "fit": fit,
        "coords": coords,
        "diagnostics": diag_df,
        "metrics": metrics_df,
        "group_counts": group_counts,
        "figures": [fig1, fig2, fig3],
        "zip_path": zip_path,
    }


if __name__ == "__main__":
    run_vgib_tsne_visualization()

tsne_results = run_vgib_tsne_visualization(
    data_path='/content/data.csv',
    micro_path='/content/micro.csv',
    brain_path='/content/all_brain_result_1(3).csv',
    out_dir='/content/icdm_tsne_visualization_outputs',
    edge_rep='log1p',
    beta=5e-4,
    gamma=1.0,
    seed=42,
    perplexity=25,
    epochs=260,
    hidden_dim=64,
    latent_dim=32,
    n_species=50,
    threshold_policy='max_risk_f1',
)

"""## Preview generated figures

"""

from IPython.display import Image, display
display(Image('/content/icdm_tsne_visualization_outputs/TSNE_01_before_after_vgib_true_label.png'))
display(Image('/content/icdm_tsne_visualization_outputs/TSNE_02_vgib_prediction_groups.png'))
display(Image('/content/icdm_tsne_visualization_outputs/TSNE_03_vgib_predicted_risk_probability.png'))

"""## Download zip

"""

from google.colab import files
files.download('/content/icdm_tsne_visualization_outputs/icdm_tsne_visualization_outputs.zip')